
-- LOWER

SELECT C.NOME, LOWER(C.NOME) FROM CLIENTES C

-- UPPER

SELECT C.NOME, LOWER(C.NOME), UPPER(C.NOME) FROM CLIENTES C;



-- INITCAP

SELECT P.NOME_DO_PRODUTO, INITCAP(P.NOME_DO_PRODUTO) FROM PRODUTOS P;


-- CONCAT

SELECT C.ENDERECO_1, C.BAIRRO, CONCAT(CONCAT(C.ENDERECO_1, ' '), C.BAIRRO) FROM CLIENTES C;

SELECT C.ENDERECO_1 || ' ' || C.BAIRRO FROM CLIENTES C;

-- LPAD

SELECT P.NOME_DO_PRODUTO, LPAD(P.NOME_DO_PRODUTO, 80, '-') FROM PRODUTOS P;

-- RPAD

SELECT P.EMBALAGEM, RPAD(P.EMBALAGEM, 20, '-') FROM PRODUTOS P;

-- SUBSTR

SELECT P.NOME_DO_PRODUTO, SUBSTR(P.NOME_DO_PRODUTO, 3,5) FROM PRODUTOS P;

-- INSTR

SELECT P.NOME_DO_PRODUTO, INSTR(P.NOME_DO_PRODUTO, 'Campo') FROM PRODUTOS P;

SELECT C.NOME FROM CLIENTES C WHERE INSTR(C.NOME, 'Mattos') <> 0;

-- LTRIM

SELECT '           VINICIUS',LTRIM( '           VINICIUS')  FROM DUAL;

-- RTRIM

SELECT  '           VINICIUS           ', RTRIM('           VINICIUS           ') FROM DUAL;

-- REPLACE

SELECT P.NOME_DO_PRODUTO, REPLACE(P.NOME_DO_PRODUTO, 'Litro', 'L') FROM PRODUTOS P;

