CREATE TABLE TB_PRODUTOS(
PRODUTO VARCHAR2(20),
NOME VARCHAR2(150),
EMBALAGEM VARCHAR2(50),
TAMANHO VARCHAR2(50),
SABOR VARCHAR2(50),
PRECO_LISTA NUMBER
);

-- Tabela nova
CREATE TABLE TB_PRODUTOS
(PRODUTO VARCHAR (20) ,
NOME VARCHAR (150) ,
EMBALAGEM VARCHAR (50) ,
TAMANHO VARCHAR (50) ,
SABOR VARCHAR (50) ,
PRECO_LISTA FLOAT);