SELECT NOME, PERCENTUAL_COMISSAO FROM TB_VENDEDORES WHERE MATRICULA = '00729';
SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO < 0.17;
SELECT * FROM TB_VENDEDORES WHERE DATA_ADMISSAO >= '01/01/2020';

-- FRILTROS COMPOSTOS
SELECT * FROM TB_VENDEDORES WHERE PERCENTUAL_COMISSAO <= 0.15 OR PERCENTUAL_COMISSAO >= 0.19;
