SELECT SOMA_EMBALAGENS.EMBALAGEM, SOMA_EMBALAGENS.SOMA_PRECO
FROM
(
SELECT P.EMBALAGEM, SUM(P.PRECO_DE_LISTA) AS SOMA_PRECO
FROM PRODUTOS P GROUP BY EMBALAGEM
) SOMA_EMBALAGENS
WHERE SOMA_EMBALAGENS.SOMA_PRECO >= 80;

CREATE VIEW VW_SOMA_EMBALAGENS AS
SELECT P.EMBALAGEM, SUM(P.PRECO_DE_LISTA) AS SOMA_PRECO
FROM PRODUTOS P GROUP BY EMBALAGEM

SELECT VSE.EMBALAGEM, VSE.SOMA_PRECO
FROM VW_SOMA_EMBALAGENS VSE
WHERE VSE.SOMA_PRECO >= 80;


