select * from notas_fiscais;
SELECT * FROM VENDEDORES;
SELECT * FROM CLIENTES;

SELECT NF.MATRICULA, COUNT(*) AS VENDAS_POR_VENDEDOR
FROM NOTAS_FISCAIS NF
GROUP BY NF.MATRICULA


SELECT V.MATRICULA, V.NOME, COUNT(*) AS VENDAS_POR_VENDEDOR
FROM VENDEDORES V
INNER JOIN NOTAS_FISCAIS NF
ON V.MATRICULA = NF.MATRICULA
GROUP BY V.MATRICULA, V.NOME;

SELECT C.CPF, C.NOME,NF.CPF
FROM CLIENTES C
INNER JOIN NOTAS_FISCAIS NF
ON C.CPF = NF.CPF


-- Adicionando um novo cliente;

INSERT INTO CLIENTES 
(CPF, NOME, ENDERECO_1, ENDERECO_2, BAIRRO, CIDADE, ESTADO, CEP, DATA_DE_NASCIMENTO, IDADE, 
SEXO, LIMITE_DE_CREDITO, VOLUME_DE_COMPRA, PRIMEIRA_COMPRA) 
VALUES ('23412632331', 'Juliana Silva', 'R. Tramandai', '', 'Bangu', 'Rio de Janeiro', 
'RJ', '23400000', TO_DATE('1989-02-04','YYYY-MM-DD'), 28, 'F', 180000.0000, 24500, 0);


SELECT DISTINCT C.CPF, C.NOME
FROM CLIENTES C
LEFT JOIN NOTAS_FISCAIS NF
ON C.CPF = NF.CPF
WHERE NF.CPF IS NULL;


SELECT V.NOME AS NOME_DO_VENDEDOR, V.BAIRRO AS BAIRRO_DO_VENDEDOR,C.NOME AS NOME_DO_CLIENTE, C.BAIRRO AS BAIRRO_DO_CLIENTE
FROM CLIENTES C
INNER JOIN VENDEDORES V
ON C.BAIRRO = V.BAIRRO;

SELECT V.NOME AS NOME_DO_VENDEDOR, V.BAIRRO AS BAIRRO_DO_VENDEDOR,C.NOME AS NOME_DO_CLIENTE, C.BAIRRO AS BAIRRO_DO_CLIENTE
FROM CLIENTES C
RIGHT JOIN VENDEDORES V
ON C.BAIRRO = V.BAIRRO;

SELECT V.NOME AS NOME_DO_VENDEDOR, V.BAIRRO AS BAIRRO_DO_VENDEDOR,C.NOME AS NOME_DO_CLIENTE, C.BAIRRO AS BAIRRO_DO_CLIENTE
FROM CLIENTES C
FULL JOIN VENDEDORES V
ON C.BAIRRO = V.BAIRRO;

SELECT C.BAIRRO FROM CLIENTES C
UNION 
SELECT V.BAIRRO FROM VENDEDORES V

SELECT C.BAIRRO FROM CLIENTES C
UNION ALL
SELECT V.BAIRRO FROM VENDEDORES V

