SELECT * FROM PRODUTOS;

SELECT * FROM PRODUTOS P ORDER BY  P.PRECO_DE_LISTA;

SELECT * FROM PRODUTOS P  WHERE ROWNUM <= 10 ORDER BY  P.PRECO_DE_LISTA; 

SELECT * FROM PRODUTOS P ORDER BY P.EMBALAGEM, P.PRECO_DE_LISTA;

SELECT * FROM PRODUTOS P ORDER BY P.EMBALAGEM, P.PRECO_DE_LISTA DESC;

