SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Melancia';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Limao';
SELECT * FROM TB_PRODUTOS WHERE SABOR = 'Citricos';
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA > 16.008;
SELECT * FROM TB_PRODUTOS WHERE PRECO_LISTA = 16.008;