SELECT * FROM TB_CLIENTES WHERE IDADE = 22;
SELECT * FROM TB_CLIENTES WHERE IDADE > 22;
SELECT * FROM TB_CLIENTES WHERE IDADE >= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <= 22;
SELECT * FROM TB_CLIENTES WHERE IDADE <> 22;
SELECT * FROM TB_CLIENTES WHERE NOME > 'Marcelo Mattos'
SELECT * FROM TB_CLIENTES WHERE NOME <> 'Marcelo Mattos'