CREATE TABLE VENDEDORES(
	MATRICULA NVARCHAR2(5) NOT NULL,
	NOME NVARCHAR2(100) NULL,
	PERCENTUAL_COMISSAO FLOAT NULL,
	DATA_ADMISSAO DATE NULL,
	DE_FERIAS NUMBER(1) NULL,
	BAIRRO NVARCHAR2(50) NULL);
 